# v0.2.16
# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }
from genlayer import *
from dataclasses import dataclass
import json

# ==============================================================================
# GENLAYER INTELLIGENT CONTRACT PRIMITIVE: QUALITATIVE PR & BOUNTY VERIFIER
# ==============================================================================
#
# OVERVIEW:
# This contract implements a decentralized, AI-driven code evaluation primitive
# on GenLayer. It enables trustless developer bounties, automated pull request
# auditing, and milestone verification without requiring centralized intermediaries.
#
# HOW CONSENSUS WORKS (THE EQUIVALENCE PRINCIPLE):
# 1. Non-Determinism:
#    Fetching web resources (gl.nondet.web.get) and executing LLM prompts
#    (gl.nondet.exec_prompt) are non-deterministic operations. Two validator nodes
#    querying an LLM or a remote web server may receive slightly different wording
#    or timing variations.
#
# 2. Leader & Validator Separation:
#    Under GenLayer's Equivalence Principle, a Leader node runs the non-deterministic
#    routine (leader_fn) to fetch the GitHub PR diff and prompt the LLM to grade the
#    code against the Acceptance Criteria. The Leader proposes its result.
#
# 3. Independent Re-Execution & Semantic Verification:
#    Validator nodes independently run the validator_fn. Crucially, validator nodes
#    do NOT rely on naive byte-by-byte or strict JSON equality of the full output,
#    because LLMs produce variable reasoning text. Instead, the validator independently
#    evaluates the PR and performs SEMANTIC EQUIVALENCE:
#        return leader_verdict == my_verdict
#    If both agree on the substantive verdict ("ACCEPTED", "REVISIONS_NEEDED", or
#    "REJECTED"), consensus is achieved.
#
# 4. State Isolation in Nondet Blocks:
#    Neither leader_fn nor validator_fn accesses contract storage or 'self' directly.
#    All required state (such as pr_url and acceptance_criteria) is read beforehand
#    and captured immutably via closure.
#
# 5. Standalone Evaluation Oracle:
#    In addition to full bounty management, this primitive exposes
#    'evaluate_pr_standalone', allowing any external smart contract or dApp to
#    utilize the AI PR verification engine on demand.
# ==============================================================================


@allow_storage
@dataclass
class Bounty:
    """
    Storage structure representing a developer bounty.
    Uses @allow_storage and @dataclass to enable GenVM pickling.
    """
    bounty_id: str
    creator: Address
    title: str
    repo_url: str
    acceptance_criteria: str
    reward_amount: bigint
    status: str             # "OPEN", "COMPLETED", "CANCELLED"
    winner: Address         # Address of the accepted contributor
    accepted_pr_url: str    # URL of the accepted pull request
    created_at_block: bigint
    total_submissions: bigint


@allow_storage
@dataclass
class PRSubmission:
    """
    Storage structure representing a PR evaluation submission and audit trail.
    """
    submission_id: str
    bounty_id: str
    claimant: Address
    pr_url: str
    verdict: str            # "ACCEPTED", "REVISIONS_NEEDED", "REJECTED", "UNRESOLVED"
    feedback: str           # Consensus reasoning generated by the LLM
    submitted_at_block: bigint


def _extract_repo_path(url: str) -> str:
    """
    Extracts canonical 'owner/repo' identifier from a GitHub repository or PR URL.
    Normalizes lowercase, strips trailing slashes, and removes '.git' suffix.
    Returns '' if the URL is not a valid GitHub repository or PR URL.
    """
    clean = url.strip()
    if "://" in clean:
        clean = clean.split("://", 1)[1]
    parts = [p.strip() for p in clean.split("/") if p.strip()]
    if len(parts) >= 3 and "github.com" in parts[0].lower():
        owner = parts[1].lower()
        repo = parts[2].lower()
        if repo.endswith(".git"):
            repo = repo[:-4]
        return f"{owner}/{repo}"
    return ""


def _get_current_block_or_timestamp() -> bigint:
    """
    Returns current block number or transaction timestamp context.
    In GenLayer GenVM Python runtime (v0.2.16 / v0.3.0), 'gl.block.number'
    is not exposed and raises AttributeError. GenVM instead provides the transaction
    timestamp via 'gl.message_raw["datetime"]'. We record this live timestamp as
    freshness context, falling back gracefully to bigint(0).
    """
    try:
        if hasattr(gl, "block") and hasattr(gl.block, "number"):
            return bigint(gl.block.number)
    except Exception:
        pass

    try:
        raw_dt = gl.message_raw.get("datetime", "")
        if raw_dt:
            if raw_dt.endswith("Z"):
                raw_dt = raw_dt[:-1] + "+00:00"
            import datetime
            dt = datetime.datetime.fromisoformat(raw_dt)
            return bigint(int(dt.timestamp()))
    except Exception:
        pass

    return bigint(0)


class Contract(gl.Contract):
    """
    Intelligent Contract primitive for automated PR and bounty auditing.
    """
    bounties: TreeMap[str, Bounty]
    bounty_ids: DynArray[str]
    submissions: TreeMap[str, PRSubmission]
    submission_ids: DynArray[str]
    bounty_counter: bigint
    submission_counter: bigint
    owner: Address

    def __init__(self):
        # Only initialize scalar values. Collections (TreeMap, DynArray) are
        # auto-initialized by GenVM and must never be reassigned in __init__.
        self.bounty_counter = bigint(0)
        self.submission_counter = bigint(0)
        self.owner = gl.message.sender_address

    # --------------------------------------------------------------------------
    # INTERNAL CONSENSUS ENGINE (EQUIVALENCE PRINCIPLE)
    # --------------------------------------------------------------------------

    def _execute_pr_evaluation(self, pr_url: str, criteria: str) -> dict:
        """
        Executes decentralized evaluation of a PR against acceptance criteria
        using gl.vm.run_nondet with semantic consensus.
        """
        # Read parameters beforehand; DO NOT access 'self' inside nondet routines
        captured_url = pr_url
        captured_criteria = criteria

        def leader_fn() -> dict:
            pr_content = ""
            target_url = captured_url

            # Optimize for GitHub PR URLs: fetching .diff provides pure unified diff
            if "github.com" in captured_url and not captured_url.endswith(".diff") and "/pull/" in captured_url:
                target_url = f"{captured_url.rstrip('/')}.diff"

            try:
                resp = gl.nondet.web.get(target_url)
                pr_content = resp.body.decode("utf-8", errors="ignore")
            except Exception:
                try:
                    # Fallback to direct URL fetch if .diff endpoint fails
                    resp = gl.nondet.web.get(captured_url)
                    pr_content = resp.body.decode("utf-8", errors="ignore")
                except Exception as fetch_err:
                    pr_content = f"Failed to retrieve PR content: {str(fetch_err)}"

            # Cap diff length to prevent exceeding LLM context window tokens
            max_chars = 12000
            if len(pr_content) > max_chars:
                pr_content = pr_content[:max_chars] + "\n... [diff truncated for length] ..."

            # Formulate structured prompt enforcing strict JSON output
            prompt = (
                "You are an expert GitHub Pull Request reviewer and impartial smart contract judge.\n"
                "Your objective is to evaluate whether the code changes in the Pull Request satisfy the Acceptance Criteria.\n\n"
                f"Acceptance Criteria:\n{captured_criteria}\n\n"
                f"PR URL: {captured_url}\n\n"
                f"PR Content / Diff:\n{pr_content}\n\n"
                "Evaluation Guidelines:\n"
                "1. Thoroughly verify if all acceptance criteria requirements are satisfied.\n"
                "2. Choose one of the following exact verdicts:\n"
                "   - ACCEPTED: All criteria are fully implemented, functional, and of acceptable quality.\n"
                "   - REVISIONS_NEEDED: The submission is relevant but requires minor changes, missing edge cases, or improvements.\n"
                "   - REJECTED: The submission fails core criteria, is unrelated, empty, or broken.\n"
                "3. Respond ONLY with a valid JSON object matching this schema:\n"
                '{"verdict": "ACCEPTED" | "REVISIONS_NEEDED" | "REJECTED", "reason": "concise explanation"}\n'
            )

            raw_resp = gl.nondet.exec_prompt(prompt, response_format="json")

            try:
                if isinstance(raw_resp, dict):
                    parsed = raw_resp
                else:
                    clean_json = str(raw_resp).strip()
                    if clean_json.startswith("```"):
                        lines = clean_json.splitlines()
                        if lines and lines[0].startswith("```"):
                            lines = lines[1:]
                        if lines and lines[-1].startswith("```"):
                            lines = lines[:-1]
                        clean_json = "\n".join(lines).strip()

                    start_i = clean_json.find("{")
                    end_i = clean_json.rfind("}")
                    if start_i != -1 and end_i != -1 and end_i > start_i:
                        clean_json = clean_json[start_i:end_i+1]

                    parsed = json.loads(clean_json)

                verdict = str(parsed.get("verdict", "")).strip().upper()
                if verdict not in ("ACCEPTED", "REVISIONS_NEEDED", "REJECTED"):
                    verdict = "REJECTED"
                reason = str(parsed.get("reason", "")).strip()
                if not reason:
                    reason = "No reasoning provided by LLM."
            except Exception as e:
                verdict = "REJECTED"
                reason = f"Failed to parse evaluation response: {str(e)}"

            return {"verdict": verdict, "reason": reason}

        def validator_fn(leader_res) -> bool:
            """
            Validator logic running independently on non-leader nodes.
            Unpacks leader result and validates semantic equivalence on verdict.
            """
            if hasattr(leader_res, "calldata"):
                leader_val = leader_res.calldata
            else:
                leader_val = leader_res

            if not isinstance(leader_val, dict):
                return False

            leader_verdict = str(leader_val.get("verdict", "")).strip().upper()
            if leader_verdict not in ("ACCEPTED", "REVISIONS_NEEDED", "REJECTED"):
                return False

            # Validator re-executes evaluation independently
            my_val = leader_fn()
            if not isinstance(my_val, dict):
                return False

            my_verdict = str(my_val.get("verdict", "")).strip().upper()

            # Compare semantic verdict meaning only, ignoring variations in reasoning text
            return leader_verdict == my_verdict

        # Execute consensus through the GenLayer VM using sandboxed run_nondet
        consensus_result = gl.vm.run_nondet(leader_fn, validator_fn)

        if hasattr(consensus_result, "calldata"):
            final_data = consensus_result.calldata
        else:
            final_data = consensus_result

        return final_data

    # --------------------------------------------------------------------------
    # PUBLIC WRITE METHODS
    # --------------------------------------------------------------------------

    @gl.public.write
    def create_bounty(
        self,
        title: str,
        repo_url: str,
        acceptance_criteria: str,
        reward_amount: bigint
    ) -> str:
        """
        Creates a new task bounty with qualitative acceptance criteria.
        Returns the unique bounty_id.
        """
        if not title or not title.strip():
            raise gl.vm.UserError("Bounty title cannot be empty")

        if not repo_url or not repo_url.strip():
            raise gl.vm.UserError("Repository URL cannot be empty")

        if not (repo_url.startswith("https://") or repo_url.startswith("http://")):
            raise gl.vm.UserError("Repository URL must begin with http:// or https://")

        if not acceptance_criteria or not acceptance_criteria.strip():
            raise gl.vm.UserError("Acceptance criteria cannot be empty")

        if reward_amount < bigint(0):
            raise gl.vm.UserError("Reward amount cannot be negative")

        self.bounty_counter = self.bounty_counter + bigint(1)
        bounty_id = f"bounty_{str(self.bounty_counter)}"

        zero_address = Address("0x0000000000000000000000000000000000000000")
        current_block = _get_current_block_or_timestamp()

        new_bounty = Bounty(
            bounty_id=bounty_id,
            creator=gl.message.sender_address,
            title=title.strip(),
            repo_url=repo_url.strip(),
            acceptance_criteria=acceptance_criteria.strip(),
            reward_amount=reward_amount,
            status="OPEN",
            winner=zero_address,
            accepted_pr_url="",
            created_at_block=current_block,
            total_submissions=bigint(0)
        )

        self.bounties[bounty_id] = new_bounty
        self.bounty_ids.append(bounty_id)

        return bounty_id

    @gl.public.write
    def submit_pr_for_evaluation(self, bounty_id: str, pr_url: str) -> str:
        """
        Submits a GitHub PR URL for automated evaluation against bounty criteria.
        Triggers non-deterministic consensus across validators.
        Returns a JSON string detailing submission outcome and bounty status.
        """
        if not bounty_id or not bounty_id.strip():
            raise gl.vm.UserError("Bounty ID cannot be empty")

        if bounty_id not in self.bounties:
            raise gl.vm.UserError("Bounty does not exist")

        bounty = self.bounties[bounty_id]

        if bounty.status != "OPEN":
            raise gl.vm.UserError(f"Bounty is not open for submissions. Current status: {bounty.status}")

        claimant = gl.message.sender_address
        if claimant == bounty.creator:
            raise gl.vm.UserError("Bounty creator cannot submit PR to their own bounty")

        if not pr_url or not pr_url.strip():
            raise gl.vm.UserError("PR URL cannot be empty")

        clean_pr_url = pr_url.strip()
        if not (clean_pr_url.startswith("https://") or clean_pr_url.startswith("http://")):
            raise gl.vm.UserError("PR URL must begin with http:// or https://")

        if "github.com" not in clean_pr_url or "/pull/" not in clean_pr_url:
            raise gl.vm.UserError("PR URL must be a valid GitHub pull request URL containing /pull/")

        # Strict validation: PR must belong to the exact repository configured for the bounty
        bounty_repo = _extract_repo_path(bounty.repo_url)
        pr_repo = _extract_repo_path(clean_pr_url)
        if not bounty_repo or not pr_repo or bounty_repo != pr_repo:
            raise ValueError("Security Error: The submitted Pull Request does not belong to this bounty's repository.")

        # Execute decentralized consensus evaluation
        eval_data = self._execute_pr_evaluation(clean_pr_url, bounty.acceptance_criteria)

        verdict = str(eval_data.get("verdict", "UNRESOLVED")).strip().upper()
        reason = str(eval_data.get("reason", "No reason recorded."))

        self.submission_counter = self.submission_counter + bigint(1)
        submission_id = f"sub_{str(self.submission_counter)}"
        current_block = _get_current_block_or_timestamp()

        new_submission = PRSubmission(
            submission_id=submission_id,
            bounty_id=bounty_id,
            claimant=claimant,
            pr_url=clean_pr_url,
            verdict=verdict,
            feedback=reason,
            submitted_at_block=current_block
        )

        self.submissions[submission_id] = new_submission
        self.submission_ids.append(submission_id)

        bounty.total_submissions = bounty.total_submissions + bigint(1)

        # Update bounty state upon successful acceptance
        if verdict == "ACCEPTED":
            bounty.status = "COMPLETED"
            bounty.winner = claimant
            bounty.accepted_pr_url = clean_pr_url

        self.bounties[bounty_id] = bounty

        response_dict = {
            "submission_id": submission_id,
            "bounty_id": bounty_id,
            "verdict": verdict,
            "reason": reason,
            "bounty_status": bounty.status
        }
        return json.dumps(response_dict)

    @gl.public.write
    def evaluate_pr_standalone(self, pr_url: str, acceptance_criteria: str) -> str:
        """
        Standalone AI evaluation primitive.
        Allows external callers or smart contracts to verify any GitHub PR
        against acceptance criteria without creating a bounty escrow.
        Returns a JSON string containing the verdict and rationale.
        """
        if not pr_url or not pr_url.strip():
            raise gl.vm.UserError("PR URL cannot be empty")

        clean_pr_url = pr_url.strip()
        if not (clean_pr_url.startswith("https://") or clean_pr_url.startswith("http://")):
            raise gl.vm.UserError("PR URL must begin with http:// or https://")

        if "github.com" not in clean_pr_url or "/pull/" not in clean_pr_url:
            raise gl.vm.UserError("PR URL must be a valid GitHub pull request URL containing /pull/")

        if not acceptance_criteria or not acceptance_criteria.strip():
            raise gl.vm.UserError("Acceptance criteria cannot be empty")

        eval_data = self._execute_pr_evaluation(clean_pr_url, acceptance_criteria.strip())

        verdict = str(eval_data.get("verdict", "UNRESOLVED")).strip().upper()
        reason = str(eval_data.get("reason", "No reason recorded."))

        result_dict = {
            "pr_url": clean_pr_url,
            "verdict": verdict,
            "reason": reason
        }
        return json.dumps(result_dict)

    @gl.public.write
    def cancel_bounty(self, bounty_id: str) -> str:
        """
        Cancels an open bounty. Can only be invoked by the creator or contract owner.
        """
        if not bounty_id or not bounty_id.strip():
            raise gl.vm.UserError("Bounty ID cannot be empty")

        if bounty_id not in self.bounties:
            raise gl.vm.UserError("Bounty does not exist")

        bounty = self.bounties[bounty_id]
        sender = gl.message.sender_address

        if sender != bounty.creator and sender != self.owner:
            raise gl.vm.UserError("Unauthorized: only creator or contract owner can cancel bounty")

        if bounty.status != "OPEN":
            raise gl.vm.UserError(f"Cannot cancel bounty with status: {bounty.status}")

        bounty.status = "CANCELLED"
        self.bounties[bounty_id] = bounty

        return f"Bounty {bounty_id} cancelled"

    # --------------------------------------------------------------------------
    # PUBLIC VIEW METHODS
    # --------------------------------------------------------------------------

    @gl.public.view
    def get_bounty(self, bounty_id: str) -> Bounty:
        """
        Returns full bounty details for a given bounty_id.
        """
        if bounty_id not in self.bounties:
            raise gl.vm.UserError("Bounty not found")
        return self.bounties[bounty_id]

    @gl.public.view
    def get_bounty_count(self) -> bigint:
        """
        Returns total number of created bounties.
        """
        return self.bounty_counter

    @gl.public.view
    def get_bounty_id_at(self, index: bigint) -> str:
        """
        Returns the bounty_id at the specified index in the bounty_ids DynArray.
        """
        idx = int(index)
        if idx < 0 or idx >= len(self.bounty_ids):
            raise gl.vm.UserError("Index out of bounds")
        return self.bounty_ids[idx]

    @gl.public.view
    def get_all_bounty_ids(self) -> DynArray[str]:
        """
        Returns the DynArray of all bounty IDs.
        """
        return self.bounty_ids

    @gl.public.view
    def get_submission(self, submission_id: str) -> PRSubmission:
        """
        Returns full submission details for a given submission_id.
        """
        if submission_id not in self.submissions:
            raise gl.vm.UserError("Submission not found")
        return self.submissions[submission_id]

    @gl.public.view
    def get_submission_count(self) -> bigint:
        """
        Returns total number of evaluated submissions.
        """
        return self.submission_counter

    @gl.public.view
    def get_submission_id_at(self, index: bigint) -> str:
        """
        Returns the submission_id at the specified index in the submission_ids DynArray.
        """
        idx = int(index)
        if idx < 0 or idx >= len(self.submission_ids):
            raise gl.vm.UserError("Index out of bounds")
        return self.submission_ids[idx]

    @gl.public.view
    def get_all_submission_ids(self) -> DynArray[str]:
        """
        Returns the DynArray of all submission IDs.
        """
        return self.submission_ids
